# Generated by Django 5.0.2 on 2024-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
                ('alcoholica', models.BooleanField()),
                ('cantidadml', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
